#!/bin/sh
wget -O gtk3.tar https://gitlab.gnome.org/GNOME/gtk/-/archive/gtk-3-24/gtk-gtk-3-24.tar?path=gtk/theme/Adwaita
tar --strip-components=3 -xf gtk3.tar gtk-gtk-3-24-gtk-theme-Adwaita/gtk/theme/Adwaita
rm gtk3.tar
cd Adwaita
patch -p1 < ../gtk3.patch
# REQUIRES: sassc
./parse-sass.sh

cd ..
wget https://dl.suckless.org/st/st-0.9.tar.gz
tar -xzf st-0.9.tar.gz
rm st-0.9.tar.gz
cd st-0.9
patch -p1 < ../st.patch
make
