#!/bin/sh

mkdir -p ~/.config/nvim

ln -fs $PWD/.bashrc    ~/.bashrc
ln -fs $PWD/.gitconfig ~/.gitconfig
ln -fs $PWD/.inputrc   ~/.inputrc
ln -fs $PWD/.tmux.conf ~/.tmux.conf
ln -fs $PWD/.vimrc     ~/.vimrc
ln -fs $PWD/init.lua   ~/.config/nvim/init.lua
